use_frameworks!

target 'SAGeometry_Example' do
  pod 'SAGeometry', :path => '../'

  target 'SAGeometry_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
